In [ ]:
# 載入影像檔案


import cv2


# 1. 用 opencv 的 imread 來讀取

# 要注意路徑不能有中文

my_image = cv2.imread("image/Haku.jpg")


# 2. 顯示影像

# 目前 Jupyter Notebook 不支援 opencv 影像顯示，但還是打出來

# cv2.imshow("my image",my_image)



In [4]:
# 對影像像素進行操作


import cv2
import numpy


# 1. 影像其實是一個 numpy array，是 n * m * 3 的 3D 矩陣

# n 就是 n 列個像素，m 就是 m 列個像素，3 就是有 3 個顏色 BGR 的強度

# 可以想成 n * m 個 2D 的矩陣，但是元素是 list，裡面有 3 個元素 ( 或者說 3 列，因為就像 n 列就是 n * m 矩陣，所以 3 個元素可以想成 3 列，表示 n * m * 3 )

my_image = cv2.imread("image/Haku.jpg")

print(numpy.shape(my_image))


# 2. 也因此只要用指派的方式將每個像素 BGR 的數值改變，就可以顯示不同的東西

# 這邊用一個小的影像加在大影像的左上角，或者說把大影像的部分像素改成小影像的數值，就達到這個效果

# 先讀取小影像的像素矩陣

my_image_2 = cv2.imread("image/Haku_2.jpg")

print(numpy.shape(my_image_2))

# 再將大影像的部分矩陣指派為小影像的像素資料

my_image_3 = numpy.copy(my_image)

row = numpy.shape(my_image_2)[0]

column = numpy.shape(my_image_2)[1]

for i in range(row) : 

    for j in range(column) : 

        my_image_3[i,j] = my_image_2[i,j]

print(my_image_3)



(372, 650, 3)
(80, 146, 3)
[[[101  82   0]
  [111  93   4]
  [114  93   1]
  ...
  [ 25   6   0]
  [ 33  17   5]
  [ 14   1   0]]

 [[103  86   0]
  [115  99  10]
  [118  99   8]
  ...
  [ 62  41  19]
  [ 48  32  19]
  [ 19   7   0]]

 [[ 97  86   0]
  [111 100  10]
  [115  98  11]
  ...
  [ 66  45  17]
  [ 58  43  24]
  [ 21   8   0]]

 ...

 [[  0   2   0]
  [  0   2   0]
  [  0   3   1]
  ...
  [ 49  23  11]
  [ 38  15   7]
  [ 25   4   0]]

 [[  0   1   1]
  [  0   1   1]
  [  0   1   1]
  ...
  [ 43  24  16]
  [ 30  11   6]
  [ 19   2   0]]

 [[  0   1   1]
  [  0   1   1]
  [  0   1   1]
  ...
  [ 20   4   0]
  [ 23   6   3]
  [ 16   1   0]]]
