In [ ]:
# 內建數字函數和常見的 Math 函數練習 ( 這邊是 int , float ... 型別的方法，因此只適用於數字 )



import math



# 1. int() 和 float()

# 將型別轉換為整數和浮點數(有小數點的數字)

str = "123"

int_num = int(str)

float_num = float(str)

print(int_num)

print(float_num)



# 2. round() , ceil() 和 floor()

# 將數字做四捨五入，向上四捨五入，向下四捨五入

num = 100.23

# round 四捨五入，可以指定要到第幾位

round_num = round(num,ndigits=1)

print(round_num)

# ceil 和 floor 是向上和向下四捨五入取到整數

upper_round_num = math.ceil(num)

lower_round_num = math.floor(num)

print(upper_round_num)

print(lower_round_num)



# 3. abs() 

# 將數字取絕對值

negative_num = -100.23

abs_num = abs(negative_num)

print(abs_num)



# 4. pow() , sqrt()

# 將數字做 n 次方或取平方根

# ( n 次方可以用 ** 來代替，a**b 表示 a 的 b 次方 )

pow_num = pow(num,3)

# 雖然 sqrt 只能做平方根，但可以用 pow 加上指數為分數來代替

sqrt_num = math.sqrt(num)

pow_num_2 = pow(num,1/2)

print(pow_num)

print(sqrt_num)

print(pow_num_2)



# 5. exp() , log() 

# 將數字做自然指數或對數 ( 底數預設為 e , log 可以用 log2 或 log10 當底數 )

exp_num = math.exp(2)

log_num = math.log(2)

print(exp_num)

print(log_num)



# 6. max() , min()

# 將一群數列裡面的最大和最小值找出來

# 基本上是 list 常用的函數，有多型的使用

num_list = [1,2,3]

max_num = max(num_list)

min_num = min(num_list)

print(max_num)

print(min_num)






123
123.0
100.2
101
100
100.23
1006915.8821670001
10.011493395093462
10.011493395093462
7.38905609893065
0.6931471805599453
3
1


In [9]:
# Numpy 也有很多和 math 一樣的函數，但是 numpy 支援陣列運算，math 不支援，所以要注意輸入的變數是否為陣列

# 例如下面的例子

# 如果不能執行，就要自己把函數搭配 universal function 來改成支援陣列的形式


import math
import numpy


array_number = numpy.array([1.23,1.24,1.25,1.26])

list_number = [1.23,1.24,1.25,1.26]


# 1. log 函數

numpy_log = numpy.log10(array_number)

numpy_log_list = numpy.log10(list_number)

print(numpy_log)

print(numpy_log_list)

# math 的 log 搭配 array 或 list 都會報錯，因為不支援陣列運算

# math_log_array = math.log10(array_number)

# math_log_list = math.log10(list_number)


# 2. sum 函數

numpy_sum = numpy.sum(array_number)

numpy_sum_list = numpy.sum(list_number)

print(numpy_sum)

print(numpy_sum_list)

# math 的 sum 搭配 array 或 list 就可以，是多型的使用

math_sum_array = sum(array_number)

math_sum_list = sum(list_number)

print(math_sum_array)

print(math_sum_list)


# 3. round 函數

numpy_round = numpy.round(array_number,1)

numpy_round_list = numpy.round(list_number,1)

print(numpy_round)

print(numpy_round_list)

# math 的 round 搭配 array 或 list 就又會報錯，所以沒有多型的支援

# math_round_array = round(array_number,ndigits=1)

# math_round_list = round(list_number,ndigits=1)




[0.08990511 0.09342169 0.09691001 0.10037055]
[0.08990511 0.09342169 0.09691001 0.10037055]
4.9799999999999995
4.9799999999999995
4.9799999999999995
4.98
[1.2 1.2 1.2 1.3]
[1.2 1.2 1.2 1.3]
