In [24]:
# numpy 模組練習

    # 基本概念：numpy array 就是介於 list 和 dataframe 之間的資料結構，具有 list 的元素直接呼叫提取功能，也作為 dataframe 的基礎，可以具有欄和列

# 和 list 不同的地方 : 

    # a. array 可以是二維陣列直接提取，像是 array(0,1)

    # b. list 需要一個 list 裡面再增加 list 來增加維度，並用多層提取，像是 list[0][1]

# 和 dataframe 不同的地方 : 

    # a. array 基本上是 array 陣列，主要是以一維作為基礎

    # b. dataframe 一定有欄和列，是加上 row 和 column 的 index label ( 可以印 dataframe 和 array 就看得出差異，dataframe 列和欄有額外所以和標籤，array 沒有 )，
    
    # 並有 group by , merge , join 等資料庫有欄位資料的類似處理方法 

    # ex. numpy array = array( [1,2,3] , [4,5,6] )，numpy array 不需要 column

    # ex. pandas dataframe = dataframe( { a: [1,2,3] , b: [4,5,6] } )，pandas dataframe 需要 column

    # c. 也因為 dataframe 的列沒有文字索引，所以列只能用欄位條件產生布林值挑選 ( 除非是 pivot )，array 的列則是因為有像 list 的基本數字索引，所以可以直接用數字索引挑選，

    # 欄位的挑選部分就沒有太大差別，dataframe 是欄位文字標籤，array 是數字索引挑選

# 總結 : list 和 array 就是差在 list 是一維 [...]， array 可以是二維 [... , ...]，dataframe 和 array 就是差在 dataframe 是用文字標籤索引 ["..."]，array 是數字索引 [0,1]


import numpy



# 1. numpy 基本使用方法 ( 和 list 一模一樣 , 通常是以 list 作為基礎產生 array , 只是增加可操作維度，從 [a] 變成 [a,b] )


# a. 呼叫元素

# 一維 array

array = numpy.array( [1,2,3,4,5] )

print(array[0])

# 二維 array ( 可以發現就是 list 的二維型態作為輸入來源，所以和 list 很像 )

# 每一個元素是行，每一個 list 是列，所以 array[ a,b ] 是第 a 列 , 第 b 行

# [ [a,b,c] , [d,e,f] ] 等同於 matrix 的 [ a,b,c ] 這樣擺放

#                                        [ d,e,f ]

array_2 = numpy.array( [ [1,2,3] , [4,5,6] ] )

print(array_2[0,1])

# 如果要用 list 多層呼叫方式也是可以，基本上也是先列再行的矩陣搜尋方式

print(array_2[0][1])


# b. 切片

# 一維 array 

# 和 list 一模一樣 , 就是 " 開始元素 : 結束元素 ( 不含該元素 ) : 跳幾個 "

print(array[0:5:2])

# 二維 array ( 矩陣式切片 )

# 和 dataframe 的 loc 使用基本上一樣，只是 array 可以直接操作，不用函數，就是 [ a:b , c:d ]，a:b 是列，c:d 是欄位，

# 此外 dataframe 是用文字標籤索引，array 是用數字索引

print(array_2[0:2,0:3])

print(array_2[:,0:3])

print(array_2[0:2,:])

# b-1. 和 dafatrame 的 loc 一樣，可以省略行的部分

print(array_2[0:2])

# b-2. array 切片也可以混和 list 來選擇需要的行列 

# ( 切片和索引陣列的混和，看到 : 就是切片，看到 [0,1] 就是索引陣列 )

# ( 和 dataframe 的 loc [ : , [ ... , ... ] ] 用欄位的索引 list 配合切片來挑選一樣，

# 只是欄位部分 array 是用數字位置索引，dataframe 是用欄位文字標籤索引 )

print(array_2[0:2,[0,2]])

# b-3. 下面和上面看起來一樣，可是只要出現兩邊相同長度的陣列，就會被自動視為進階索引的使用，而不是切片，

# 但只要兩邊不同就是切片 ( 兩邊如果是不同長度的陣列會錯誤，不能這樣挑 )

print(array_2[[0,1],[0,2]])


# c. 進階索引

# 可以用索引陣列 ( 或 索引 list ) 來對應相對應維度的陣列來呼叫元素，會回傳符合條件的值的一維陣列

# 這個方法比較常被 numpy 的 where() 函數使用，因為會回傳索引陣列，需要用它來找元素

# 一維 : 

# 一個 array 即可，因為是一維

print( array[ numpy.array([0,1,2]) ] )

# 二維 : 

# 兩個 array 來代表 row 和 column 的索引，因為是二維，多維就要多個 indices array

# 然後 array 長度要一樣，因為這樣所有索引才能產生相對應維度座標

print( array_2[ [0,1,1] , [1,0,2] ] )

# 二維以上可以用切片的冒號來代表一個維度，表示那一個維度的所有元素，直接讓另一個維度來對應，是不同長度的，會產生 i * j 結果

# 基本上就是降維，只剩另一個維度來挑選哪些行或哪些列

print( array_2[ : , numpy.array([0,1]) ] )


# d. 賦值

# numpy array 和 list 一樣，只要能用前面 a , b , c 方法篩選到，基本上都可以直接賦值

# ex. array[0] = 1 , array[0:1] = 2 , array[[True,True,False]] = 2 , array[numpy.array([0,1])] = 2



# 2. numpy 的常用函數


# a. arange( i,j )

# 自動產生一個 i 個元素的陣列，從 0 開始起算，j 是停止的地方，就是 range 的 array 版本，所以叫 arange

array_3 = numpy.arange(0,5)

print(array_3)


# b. rehsape( i,j )

# 把原本 array 的維度改成 i * j 的維度，例如這邊原本 2 * 3 的維度，改成 3 * 2

array_4 = array_2.reshape(3,2)

print(array_4)

# 有時候 numpy array 做為資料來源輸入某些方法時，需要是多維矩陣 array，此時可以用 reshape 把一維 array 轉成二維，多 column 標籤 ( 本質還是一維 )

# 這邊的 -1 表示指定另一個維度後自動計算 -1 的維度有幾個， (-1,1) 結果會是把原本一維的 array 內的 n 個元素拆開各自獨立的 list，因為指定 1 個 column，所以 -1 就是分到 n 個 row

array_5 = array_2.reshape(-1,2)

# 結果和 array_4 一樣，不用指定第一個參數，另一個是 2，所以 6 個元素去分一定是 3 * 2

print(array_5)

# 例如原本是 [ a,b,c ] 的陣列，是 3 個元素單維度的 array 而已，因為只有一個 list，沒有 [[]] 這樣表示，[[a,b,c]] 才是 1 * 3 維度

# 變成 [[a],[b],[c]] 就是二維裡面有 3 個 list，所以就是 3 * 1 的維度 ( 因為一個 list 就是一個 row )

array_6 = array.reshape(-1,1)

print(array_6)


# c. concatenate() 和 stack()

# 基本上就是合併， concatenate 是同一維度的合併， stack 是增加維度的合併 ( 疊更高 )

# ( concatenate 常用在陣列是一列一筆資料的陣列，然後要合併在一起，資料列變多 )

# ( stack 常用在陣列是一欄位對應的一個序列資料的陣列，然後要反轉後合併，讓原本一欄一為一列的資料變成一欄多列的資料，符合一般 dataframe 等資料常見格式 )

# c-1. concatentate() 等同 

    # 一維 :

    # list 的 extend ( 一維合併，同一維度的擴展，所以在一維就是行的增加，舊的版本就是 x 軸方向的合併，記得第一個參數要用 tuple 包起來要合併的陣列 ) 

    # axis 可以設定為 0 或 -1，但一維的結果都一樣，都是往 x 軸方向合併

array_7 = numpy.array([6,7,8,9,10])

array_8 = numpy.concatenate((array,array_7))

print(array_8)

    # 二維 : 

    # axis = 0 ( 往 y 方向，列的方向 )

    # dataframe 的 concatenate ( 二維合併，也是在二維擴展，所以在二維就是表示 list 增加，或者說 dataframe 的增加列，
    
    # 可以參考 dataframe [ [...] , [...] ] 不同日期合併的那個例子，dataframe 的 concatenate 也是同一維度合併，所以不同日期的二維 dataframe 合併後還是同樣二維的 dataframe )

    # 例如這邊兩個 2 * 3 的 array，用列增加，所以是兩個兩列單行資料往列並排，所以是往列增加，變成 4 * 3 ，列變成 4 列 

array_9 = numpy.array([[7,8,9],[10,11,12]])

array_10 = numpy.concatenate((array_2,array_9))

print(array_10)

    # axis = 1 ( 往 x 方向，行的方向 )

    # 往 x 軸方向就是把原本二維陣列用成列，再加上另一個二維陣列用成列，變成兩行，所以是行的增加，維度一樣不變

    # 例如這邊兩個 2 * 3 的 array，用行增加，所以是兩個兩列三行資料往行並排，所以是往行增加，變成 2 * 6 ，行變成 6 行

array_10_2 = numpy.concatenate((array_2,array_9),axis=1)

print(array_10_2)

# c-2. stack() 等同

    # 一維 :

    # axis = 0 ( 往 y 方向增加，列的方向 )

    # list 的 append ( 一維合併變二維，一維變二維就是列的增加，舊的版本就是 y 軸的合併，表示增加 list 元素，可以用 stack 就是疊起來來記，就像往 y 軸疊東西 )

    # 通常 stack() 會比較常用來合併，因為是 append() 的作用，基本上在資料都是一維時很常會用，把所有資料都合併變成二維的 list of list

    # 例如這邊兩個 1 * 5 的 array，用列增加，所以是兩個單列五行的資料往列並排，往列增加，變成 2 * 5， 列變成 2 列

array_11 = numpy.stack((array,array_7))

print(array_11)

    # axis = 1 ( 往 x 方向增加，行的方向 )

    # 這招很常用，基本上就是把原本一維陣列反轉，再往行方向增加，比較符合一般 dataframe 資料往列方向排序，欄位往行排序的排列方式，同樣會增加維度

    # 例如這邊兩個 1 * 5 的 array，先做反轉變成 5 * 1 後，再將兩個五列一行的資料往行並排，變成 5 * 2， 行變成 2 行

array_11_2 = numpy.stack((array,array_7),axis=1)

print(array_11_2)

    # 二維 : ( 較少用 )
    
    # 合併就會變成三維，用一個更大的 list 來包住原本的兩個二維 array，所以變三維

    # axis = 0 ( 往 z 方向增加，新的方向，其實之前一維也可以這樣理解，一維原本只有 x 軸，stack 完往新的 y 軸增加 )

    # 就是兩個 2 * 3 的陣列往新的軸堆疊，新的軸就是新的 list，而原本的陣列就變成兩個元素放在裡面

array_12 = numpy.stack((array_2,array_9))

print(array_12)

    # axis = 1 ( 反轉 )

    # 就是前面 axis = 0 兩個 2 * 3 陣列合併後的反轉

array_12_1 = numpy.stack((array_2,array_9),axis=1)

print(array_12_1)

# c-3. hstack() 及 vstack()

# hstack 就是水平的疊加，是唯一 stack 裡面不會增加維度的用法，等同 concatenate 一維和二維的 axis = 1

# vstack 是把陣列先轉換成垂直方向，再往航的方向疊加，等同於 stack 一維的 axis = 1



# 3. numpy 常用的資料篩選方法

# 和 pandas dataframe 一樣，numpy array 也有自己的資料篩選方法，也是有布林陣列的方法


# a. 直接用 where() 函數

# 一維 : 

array_13 = numpy.array([0,10,20,30,40])

array_14 = numpy.where(array_13>25)

print(array_14)

# 會回傳一個 tuple 包著含有索引的 array，不會直接傳值回來，但可以用 numpy array 的進階索引來找符合的值

array_15 = array_13[array_14]

print(array_15)

# 二維 : 

array_16 = numpy.array([[0,10,20,30,40],[5,15,25,35,45]])

array_17 = numpy.where(array_16>33)

# 二維會回傳一個 tuple 包著兩個分別是 row 和 column 索引的 array，一定是兩個或多個長度一樣的 array，這樣才能有對應維度的座標

print(array_17)

# 放到 array 的進階索引就會自動把 row 和 column 兩個 indices array 對應成 (a,b) , (c,d) , (e,f) ... 的矩陣位置來找值

array_18 = array_16[array_17]

print(array_18)


# b. 用布林陣列來篩選

# 一維 : 

# 先產生一個布林陣列

# ( array 是 array > ... 陣列配合條件產生布林陣列，跟 dataframe 很像，dataframe 也是 dataframe[" "] > ... 欄位配合條件來產生布林陣列 )

array_19 = numpy.array(array_13>25)

print(array_19)

# 再套用在要篩選的陣列，就能篩選出符合條件的元素 

# ( array 是把條件放在 [ ] 裡面，就像 dataframe 的 [ ] 裡面放布林陣列來挑選資料 )

array_20 = array_13[array_19]

print(array_20)

# 二維 : 

# 就是布林陣列變成比較陣列的一樣維度而已

array_21 = numpy.array(array_2>1)

print(array_21)

# 回傳變成一個符合條件值的一維陣列

array_22 = array_2[array_21]

print(array_22)



1
2
2
[1 3 5]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 3]
 [4 6]]
[1 6]
[1 2 3]
[2 4 6]
[[1 2]
 [4 5]]
[0 1 2 3 4]
[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]]
[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]
(array([3, 4]),)
[30 40]
(array([0, 1, 1]), array([4, 3, 4]))
[40 35 45]
[False False False  True  True]
[30 40]
[[False  True  True]
 [ True  True  True]]
[2 3 4 5 6]


In [ ]:
# numpy 的其他基本觀念補充


import numpy



# 1. numpy 的一維單元素陣列可以直接當值來操作，不用做 int()

array = numpy.array([1])

a = array + 2 

print(a)



# 2. numpy 的基礎是 list , 所以多維陣列就是多維 list，元素會是相對應的 list


# a. 組成陣列

# 一維的 numpy 就是 一維的 list 產生

one_dimension = numpy.array([1,2,3])

# 二維的 numpy 就是 二維的 list 產生，注意是 list of list

two_dimension = numpy.array([ [1,2,3] , [4,5,6] ])

# 三維的 numpy 就是 三維的 list 產生，所以是 list of list of list

three_dimension = numpy.array([ [ [1,2] , [3,4] , [5,6] ] , [ [7,8] , [9,10] , [11,12] ] ])


# b. 呼叫元素

# 呼叫自己維度一定是最小的階層，也就是個別元素，而往上就是 list，list of list ...一直往上

# 一維 : 因為是一維，所以呼叫一維一定是元素而已

one_d_one_call = one_dimension[0]

print(one_d_one_call)

# 二維 : 二維呼叫就是某列的某行元素，最基本元素，往上一維呼叫就是列的 list，因為 array 是用列去分 list

two_d_one_call = two_dimension[0]

two_d_two_call = two_dimension[0,0]

print(two_d_one_call)

print(two_d_two_call)

# 三維 : 三維呼叫就是某列某行的第幾個元素，最基本元素，往上一維就是某列某行的 list，再往上就是某列的 list of list

three_d_one_call = three_dimension[0]

three_d_two_call = three_dimension[0,0]

three_d_three_call = three_dimension[0,0,0]

print(three_d_one_call)

print(three_d_two_call)

print(three_d_three_call)


# c. 部分切片

# 可以一樣用呼叫的層級來思考 : 

    # 全部填滿 : 最低層級 , 所以是 元素

    # 拿掉一個不填滿 : 往上一個層級，所以是 list，反過來說就是用指定的 " 列與行 " 或 " 行與高度 " 或 " 列與高度 " 來抓指定位置的 list ( 序列 )
    
    # 拿掉兩個不填滿 : 再往上一個層級，所以是 list of list，反過來說就是用指定的 " 行 " 或 " 列 " 或 " 高度 " 來抓指定行或列或高度的 list of list

# 維度的思考方式 : 

    # 固定一維 ( 拿掉兩個不填滿 ) : 一個維度固定住，只看某一維度底下的情況，例如三維固定一維，看該維度底下的其他二維平面 / list of list 情況 ( 三維變二維，二維變一維 )

    # 固定二維 ( 拿掉一個不填滿 ) : 兩個維度固定住，只看某兩個維度底下的情況，或說平面上某一點向另一軸發展的 list 情況 ( 三維變一維 )

    # 本質上就是看該指定維度的元素，指定越高維就是越確定，就會使想看的維度越低

    # 例如 : 列固定，那就是產生列的結果，只是看底下行的元素

    # 例如 : 列和行固定，那就是產生列和行交叉的結果，只是看底下高度的元素

    # 也可以想成降維，固定一維就是少一維，剩另一邊行或列在變化，固定二維就是少兩維，那就剩高度在變化

# 二維降一維 : 指定抓某一 " 列 " 或 " 行 " 的資料，

# 或說只看某一 " 行 " 或 " 列 "  底下的變化，就是二維少一維，變成一個序列而已

two_d_row_partial = two_dimension[0,:]

two_d_column_partial = two_dimension[:,0]

print(two_d_row_partial)

print(two_d_column_partial)

# 三維降一維 : 指定抓某一 " 列與行 " 或 " 行與高度 " 或 " 列與高度 " 的資料，

# 或說只看某一 " 列與行 "" 或 " 行與高度 " 或 " 列與高度 " 底下的變化，三維少二維就變成是一維的序列

three_d_row_column_partial = three_dimension[0,0,:]

three_d_row_altitude_partial = three_dimension[0,:,0]

three_d_column_altitude_partial = three_dimension[:,0,0]

print(three_d_row_column_partial)

print(three_d_row_altitude_partial)

print(three_d_column_altitude_partial)

# 三維降一維 : 指定抓某一 " 列與行 " 或 " 行與高度 " 或 " 列與高度 " 的資料，只是因為是三維，所以底下抓到的會是二維，

# 或者說只看某一 " 列 " 或 " 行 " 或 " 高度 " 底下的變化，三維少一維就變成是二維的矩陣

three_d_row_partial = three_dimension[0,:,:]

three_d_column_partial = three_dimension[:,0,:]

# 注意 : 高度 = 0 就是 list of list of list 底下最後一個 list 的第幾個元素，可以想成元素長度是高度

# 升維就是元素變成 list / 元素往某軸長度變長 : 

# 原本一維 : [1,2,3] -> 二維 : 元素長大了，也變成 list [ [1,4] , [2,5] , [3,6] ] -> 三維 : 元素再次長大變成 list [ [ [1,7],[4,8] ] , [ [2,9],[5,10] ] , [ [3,11],[6,12] ] ]

three_d_altitude_partial = three_dimension[:,:,0]

print(three_d_row_partial)

print(three_d_column_partial)

print(three_d_altitude_partial)



# 3. 全部元素呼叫


# a. 如果要呼叫全部元素，可以用 [ : ] 即可 ( list 切片的基本功能，numpy 是基於 list，也都支援切片，所以也能用 ) 

a = numpy.array([[1,2,3],[4,5,6]])

print(a[:])


# b. 也因此可以把全部元素指派其他值

a[:] = 255

print(a)


# 注意 : 


# a. 陣列 = 255 只會變成一個 255 的數值，這樣做是不對的

a = 255 

print(a)

# 只有布林陣列才可以這樣做，代表隊所有元素做比較

b = numpy.array([[1,2,3],[4,5,6]])

c = b < 4

print(c)


# b. 但是如果讀取一個 > 1 維矩陣的一部分 = n 會使使定區域全部元素為 n，蠻方便的功能

# 二維指定一個列

d = numpy.array([ [1,2] , [3,4] ])

d[0] = 1

print(d)

# 三維指定一個列

e = numpy.array([ [ [1,2],[3,4] ] , [ [5,6],[7,8] ]])

e[0] = 1

print(e)

# 如果是用全部去指派就會變單純那個數字

f = numpy.array([[1,2,3],[4,5,6]])

f = 1 

print(f)


[3]
1
[1 2 3]
1
[[1 2]
 [3 4]
 [5 6]]
[1 2]
1
[1 2 3]
[1 4]
[1 2]
[1 3 5]
[1 7]
[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [7 8]]
[[ 1  3  5]
 [ 7  9 11]]
[[1 2 3]
 [4 5 6]]
[[255 255 255]
 [255 255 255]]
255
[[ True  True  True]
 [False False False]]
[[1 1]
 [3 4]]
[[[1 1]
  [1 1]]

 [[5 6]
  [7 8]]]
1


In [5]:
# numpy 的其他函數和屬性還有技巧



import numpy



# 1. frompyfunc() 和 map() 的陣列轉換函數

# 一般的函數不支援陣列的引數和輸出，因此要用一些函數來幫助轉換成支援陣列，就像 numpy 的函數，例如 sum、log 等等，變成可以元素對元素計算

# frompyfunc 和 map 都可以做，兩者都是一個元素一個元素丟給原來函數再將獲得結果做成陣列

# frompyfunc 是支援輸出多個陣列輸入及輸出，map 只支援最多兩個輸入及一個輸出

# frompyfunc 是最後轉換完再用轉換完的函數來輸入引數，map 是直接把在轉換函數內輸入原來函數和引數


# a. frompyfunc

# 自己定義要用的函數

def sigmoid(u) :  
    
    value = 1 / (1 + numpy.exp(-u))

    return value

def add(a,b) :  

    return a + b

# 再用 frompyfun 來轉換函數成支援陣列，第二個和第三個引數分別是輸入的陣列數和輸出的陣列數

array_sigmoid = numpy.frompyfunc(sigmoid,1,1)

array_add = numpy.frompyfunc(add,2,1)

# 最後輸出就可以用轉換完的函數直接代入引數，就會自動呼叫裡面的函數來產生陣列結果

linear_y = [1,2,3]

y_prediction = array_sigmoid(linear_y)

pyfunc_add = array_add(linear_y,linear_y)

print(y_prediction)

print(pyfunc_add)


# b. map

#  一樣自己定義函數

def sigmoid(u) :  
    
    value = 1 / (1 + numpy.exp(-u))

    return value

def add(a,b) :  

    return a + b

# 用 map 來轉換成支援陣列輸入及輸出，直接輸入函數和引數

# 注意 map 輸出需要用 list 轉換才看得到

map_sigmoid = map(sigmoid,linear_y)

print(list(map_sigmoid))

map_add = map(add,linear_y,linear_y)

print(list(map_add))


# c. list 的 comprehension list 就是 frompyfunc 和 map 的一個輸入和一個輸出的用法

comprehension_list = [sigmoid(item) for item in linear_y]

print(comprehension_list)



import pandas



# 2. numpy array 轉 pandas dataframe


# a. 直接用 pandas.dataframe()

# 一維 : 會使 array 元素變成列表示

a = numpy.array([1,2,3])

a_dataframe = pandas.DataFrame(a)

print(a_dataframe)

# 二維 : 就是正常的 dataframe , dataframe 本身就是二維

b = numpy.array([[1,2,3],[4,5,6]])

b_dataframe = pandas.DataFrame(b)

print(b_dataframe)


# b. 使用 from_records()

# 基本上和 pandas.dataframe() 方法一樣，沒有差別

array_column = numpy.array(["日期","名稱","收盤價"])

array_row = numpy.array([["20250801","aaa",120],["20250802","aaa",130],["20250803","aaa",140],["20250804","aaa",150],["20250805","aaa",160]])

dataframe = pandas.DataFrame.from_records(array_row,columns=array_column)

print(dataframe)


# c. 額外技巧 : 把 numpy array 加入 dataframe 變成新的一欄

# 就是把 numpy 的 array 當成資料 list 而已

array_volumn = numpy.array([10,20,30,40,50])

array_start = numpy.array([110,120,130,140,150])

# c-1. 用一般新增欄位方法

dataframe["成交量"] = array_volumn

print(dataframe)

# c-2. 用 insert() 方法指定位置

dataframe.insert(2,column="開盤價",value=array_start)

print(dataframe)



# 3. transpose() 和 T

# numpy 有提供矩陣轉置的方法和屬性，在某些情況會很好用

# T 比較適合二維，Transpose() 比較適合二維以上

# 像是可以在資料室一行一行的情況下，像是一個一個數列，可以直接用一般方法形成矩陣，再轉置成一般的一列一列資料

# 反之亦然，如果想要畫圖，也可以轉回來變成數列

# 範例 : 

# a 是月份，一個時間序列

a_1 = [1,2,3,4,5,6]

# b 是數值，也是一個數列

a_2 = [100,110,120,130,140,150]

# 用成 array 會不符合一列一列資料的特性

a_3 = numpy.array([a_1,a_2])

print(c)

# 所以轉置一般資料列的樣子

a_4 = a_3.T

print(a_4)



[np.float64(0.7310585786300049) np.float64(0.8807970779778823)
 np.float64(0.9525741268224334)]
[2 4 6]
[np.float64(0.7310585786300049), np.float64(0.8807970779778823), np.float64(0.9525741268224334)]
[2, 4, 6]
[np.float64(0.7310585786300049), np.float64(0.8807970779778823), np.float64(0.9525741268224334)]
   0
0  1
1  2
2  3
   0  1  2
0  1  2  3
1  4  5  6
         日期   名稱  收盤價
0  20250801  aaa  120
1  20250802  aaa  130
2  20250803  aaa  140
3  20250804  aaa  150
4  20250805  aaa  160
         日期   名稱  收盤價  成交量
0  20250801  aaa  120   10
1  20250802  aaa  130   20
2  20250803  aaa  140   30
3  20250804  aaa  150   40
4  20250805  aaa  160   50
         日期   名稱  開盤價  收盤價  成交量
0  20250801  aaa  110  120   10
1  20250802  aaa  120  130   20
2  20250803  aaa  130  140   30
3  20250804  aaa  140  150   40
4  20250805  aaa  150  160   50
[[  1   2   3   4   5   6]
 [100 110 120 130 140 150]]
[[  1 100]
 [  2 110]
 [  3 120]
 [  4 130]
 [  5 140]
 [  6 150]]


In [ ]:
# numpy 常用的數學方法和數學函數



import numpy 



# 1. copy() , zeros() , zeros_like()

# copy 是可以直接複製另一個陣列，zero 則是產生元素為 0 的陣列，而 zeros_like 就是兩者的結合，複製另一個陣列並把全部元素改為 0 

# 元素型別就是以原來的陣列元素型別

array = numpy.array([[1,2,3],[4,5,6]])

array_2 = numpy.copy(array)

print(array_2)

# zeros 可以指定陣列的欄和列，只要用 tuple 在引數輸入即可，要注意預設產生浮點數

array_3 = numpy.zeros(5)

array_4 = numpy.zeros((2,3))

print(array_3)

print(array_4)

# zeros_like 就是 copy + zeros , 產生一個指定參考陣列的一樣大小的 0 陣列

# 元素型別和 copy 一樣以原來的陣列元素型別

array_5 = numpy.zeros_like(array)

print(array_5)



from numpy.random import random , rand , randint , uniform , normal



# 2. linspace() , random() , rand() , uniform() , normal()

# 後面四個 : 

# 都是 numpy random 的隨機函數，可以用 seed() 來控制隨機種子來產生一樣的結果

# 都支援產生陣列，size 引數可以給陣列的 tuple

# 基本上後面四個隨機函數不給引數就是產生一個數字，如果有其他引數就是預設第一個引數為 0 , 第二個為 1

# 例如 uniform 就是上下界為 0 , 1 , 而 random 則是 loc = 0 , scale = 1


# a. linspace()

# linespace 是均分一個區間並產生數字

# linespace 可以指定區間，例如下面隨機產生 0 到 10 中間 20 個點

x_1 = numpy.linspace(0,10,5)

print(x_1)


# b. random() 和 rand()

# random 和 rand 都是均勻分配，隨機在 0 ~ 1 之間產生數字的隨機函數

# 差別是 random 的引數是用 tuple 來描述陣列， rand 則是 n 個引數來描述陣列

# random() 和 numpy.random 底下的 random_sample() , ranf() , sample() 都一樣

# 可以自己乘上或加上數字來調整數字區間，調整方式是 min + ( max - min ) * random，像下面就變成 0 到 2

x_2 = 2*random()

print(x_2)

# rand() 也是隨機在 0 ~ 1 之間產生數字的產生器，但是是用 n 個引數來表達陣列

x_3 = 2*rand()

print(x_3)


# c. randint() 

# 是可以自己設定上下界 , size , 數字型別是 int 特性的 random 

x_4 = randint(low=0,high=255,size=(2,3))

print(x_4)


# d. uniform() 和 normal()

# uniform 和 normal 有一定的分配，且可以自己設定區間或平均數和標準差，比較方便控制區間

# uniform 第一個參數 low 是下界，第二個 high 是上界，最後一個 size 是產生數量或 tuple 陣列

a = uniform(low=-1,high=1,size=10)

print(a)

# normal 第一個參數 loc 是平均值，第二個 scale 是標準差，最後一個 size 是產生數量或 tuple 陣列

b = normal(loc=5,scale=1,size=10)

print(b)





[[1 2 3]
 [4 5 6]]
[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0]
 [0 0 0]]
[ 0.   2.5  5.   7.5 10. ]
0.9929638828300831
0.1098859043413074
[[  2   6 170]
 [168  84  22]]
[-0.17098972  0.44418007 -0.67438359 -0.37147459  0.49183344  0.61233072
  0.35380834  0.50449786 -0.35079283 -0.03438269]
[6.78655688 6.09711741 6.45549929 4.29761006 6.22716856 5.04518521
 5.51444161 6.78248768 5.21606692 4.66364035]
