In [24]:
# numpy 模組練習

    # 基本概念：numpy array 就是介於 list 和 dataframe 之間的資料結構，具有 list 的元素直接呼叫提取功能，也作為 dataframe 的基礎，可以具有欄和列

# 和 list 不同的地方 : 

    # a. array 可以是二維陣列直接提取，像是 array(0,1)

    # b. list 需要一個 list 裡面再增加 list 來增加維度，並用多層提取，像是 list[0][1]

# 和 dataframe 不同的地方 : 

    # a. array 基本上是 array 陣列，主要是以一維作為基礎

    # b. dataframe 一定有欄和列，是加上 row 和 column 的 index label ( 可以印 dataframe 和 array 就看得出差異，dataframe 列和欄有額外所以和標籤，array 沒有 )，
    
    # 並有 group by , merge , join 等資料庫有欄位資料的類似處理方法 

    # ex. numpy array = array( [1,2,3] , [4,5,6] )，numpy array 不需要 column

    # ex. pandas dataframe = dataframe( { a: [1,2,3] , b: [4,5,6] } )，pandas dataframe 需要 column

    # c. 也因為 dataframe 的列沒有文字索引，所以列只能用欄位條件產生布林值挑選 ( 除非是 pivot )，array 的列則是因為有像 list 的基本數字索引，所以可以直接用數字索引挑選，

    # 欄位的挑選部分就沒有太大差別，dataframe 是欄位文字標籤，array 是數字索引挑選

# 總結 : list 和 array 就是差在 list 是一維 [...]， array 可以是二維 [... , ...]，dataframe 和 array 就是差在 dataframe 是用文字標籤索引 ["..."]，array 是數字索引 [0,1]


import numpy



# 1. numpy 基本使用方法 ( 和 list 一模一樣 , 通常是以 list 作為基礎產生 array , 只是增加可操作維度，從 [a] 變成 [a,b] )


# a. 呼叫元素

# 一維 array

array = numpy.array( [1,2,3,4,5] )

print(array[0])

# 二維 array ( 可以發現就是 list 的二維型態作為輸入來源，所以和 list 很像 )

# 每一個元素是行，每一個 list 是列，所以 array[ a,b ] 是第 a 列 , 第 b 行

# [ [a,b,c] , [d,e,f] ] 等同於 matrix 的 [ a,b,c ] 這樣擺放

#                                        [ d,e,f ]

array_2 = numpy.array( [ [1,2,3] , [4,5,6] ] )

print(array_2[0,1])

# 如果要用 list 多層呼叫方式也是可以，基本上也是先列再行的矩陣搜尋方式

print(array_2[0][1])


# b. 切片

# 一維 array 

# 和 list 一模一樣 , 就是 " 開始元素 : 結束元素 ( 不含該元素 ) : 跳幾個 "

print(array[0:5:2])

# 二維 array ( 矩陣式切片 )

# 和 dataframe 的 loc 使用基本上一樣，只是 array 可以直接操作，不用函數，就是 [ a:b , c:d ]，a:b 是列，c:d 是欄位，

# 此外 dataframe 是用文字標籤索引，array 是用數字索引

print(array_2[0:2,0:3])

print(array_2[:,0:3])

print(array_2[0:2,:])

# b-1. 和 dafatrame 的 loc 一樣，可以省略行的部分

print(array_2[0:2])

# b-2. array 切片也可以混和 list 來選擇需要的行列 

# ( 切片和索引陣列的混和，看到 : 就是切片，看到 [0,1] 就是索引陣列 )

# ( 和 dataframe 的 loc [ : , [ ... , ... ] ] 用欄位的索引 list 配合切片來挑選一樣，

# 只是欄位部分 array 是用數字位置索引，dataframe 是用欄位文字標籤索引 )

print(array_2[0:2,[0,2]])

# b-3. 下面和上面看起來一樣，可是只要出現兩邊相同長度的陣列，就會被自動視為進階索引的使用，而不是切片，

# 但只要兩邊不同就是切片 ( 兩邊如果是不同長度的陣列會錯誤，不能這樣挑 )

print(array_2[[0,1],[0,2]])


# c. 進階索引

# 可以用索引陣列 ( 或 索引 list ) 來對應相對應維度的陣列來呼叫元素，會回傳符合條件的值的一維陣列

# 這個方法比較常被 numpy 的 where() 函數使用，因為會回傳索引陣列，需要用它來找元素

# 一維 : 

# 一個 array 即可，因為是一維

print( array[ numpy.array([0,1,2]) ] )

# 二維 : 

# 兩個 array 來代表 row 和 column 的索引，因為是二維，多維就要多個 indices array

# 然後 array 長度要一樣，因為這樣所有索引才能產生相對應維度座標

print( array_2[ [0,1,1] , [1,0,2] ] )

# 二維以上可以用切片的冒號來代表一個維度，表示那一個維度的所有元素，直接讓另一個維度來對應，是不同長度的，會產生 i * j 結果

# 基本上就是降維，只剩另一個維度來挑選哪些行或哪些列

print( array_2[ : , numpy.array([0,1]) ] )


# d. 賦值

# numpy array 和 list 一樣，只要能用前面 a , b , c 方法篩選到，基本上都可以直接賦值

# ex. array[0] = 1 , array[0:1] = 2 , array[[True,True,False]] = 2 , array[numpy.array([0,1])] = 2



# 2. numpy 的常用函數


# a. arange( i,j )

# 自動產生一個 i 個元素的陣列，從 0 開始起算，j 是停止的地方，就是 range 的 array 版本，所以叫 arange

array_3 = numpy.arange(0,5)

print(array_3)


# b. rehsape( i,j )

# 把原本 array 的維度改成 i * j 的維度，例如這邊原本 2 * 3 的維度，改成 3 * 2

array_4 = array_2.reshape(3,2)

print(array_4)

# 有時候 numpy array 做為資料來源輸入某些方法時，需要是多維矩陣 array，此時可以用 reshape 把一維 array 轉成二維，多 column 標籤 ( 本質還是一維 )

# 這邊的 -1 表示指定另一個維度後自動計算 -1 的維度有幾個， (-1,1) 結果會是把原本一維的 array 內的 n 個元素拆開各自獨立的 list，因為指定 1 個 column，所以 -1 就是分到 n 個 row

array_5 = array_2.reshape(-1,2)

# 結果和 array_4 一樣，不用指定第一個參數，另一個是 2，所以 6 個元素去分一定是 3 * 2

print(array_5)

# 例如原本是 [ a,b,c ] 的陣列，是 3 個元素單維度的 array 而已，因為只有一個 list，沒有 [[]] 這樣表示，[[a,b,c]] 才是 1 * 3 維度

# 變成 [[a],[b],[c]] 就是二維裡面有 3 個 list，所以就是 3 * 1 的維度 ( 因為一個 list 就是一個 row )

array_6 = array.reshape(-1,1)

print(array_6)


# c. concatenate() 和 stack()

# 基本上就是合併， concatenate 是同一維度的合併， stack 是增加維度的合併 ( 疊更高 )

# ( concatenate 常用在陣列是一列一筆資料的陣列，然後要合併在一起，資料列變多 )

# ( stack 常用在陣列是一欄位對應的一個序列資料的陣列，然後要反轉後合併，讓原本一欄一為一列的資料變成一欄多列的資料，符合一般 dataframe 等資料常見格式 )

# c-1. concatentate() 等同 

    # 一維 :

    # list 的 extend ( 一維合併，同一維度的擴展，所以在一維就是行的增加，舊的版本就是 x 軸方向的合併，記得第一個參數要用 tuple 包起來要合併的陣列 ) 

    # axis 可以設定為 0 或 -1，但一維的結果都一樣，都是往 x 軸方向合併

array_7 = numpy.array([6,7,8,9,10])

array_8 = numpy.concatenate((array,array_7))

print(array_8)

    # 二維 : 

    # axis = 0 ( 往 y 方向，列的方向 )

    # dataframe 的 concatenate ( 二維合併，也是在二維擴展，所以在二維就是表示 list 增加，或者說 dataframe 的增加列，
    
    # 可以參考 dataframe [ [...] , [...] ] 不同日期合併的那個例子，dataframe 的 concatenate 也是同一維度合併，所以不同日期的二維 dataframe 合併後還是同樣二維的 dataframe )

    # 例如這邊兩個 2 * 3 的 array，用列增加，所以是兩個兩列單行資料往列並排，所以是往列增加，變成 4 * 3 ，列變成 4 列 

array_9 = numpy.array([[7,8,9],[10,11,12]])

array_10 = numpy.concatenate((array_2,array_9))

print(array_10)

    # axis = 1 ( 往 x 方向，行的方向 )

    # 往 x 軸方向就是把原本二維陣列用成列，再加上另一個二維陣列用成列，變成兩行，所以是行的增加，維度一樣不變

    # 例如這邊兩個 2 * 3 的 array，用行增加，所以是兩個兩列三行資料往行並排，所以是往行增加，變成 2 * 6 ，行變成 6 行

array_10_2 = numpy.concatenate((array_2,array_9),axis=1)

print(array_10_2)

# c-2. stack() 等同

    # 一維 :

    # axis = 0 ( 往 y 方向增加，列的方向 )

    # list 的 append ( 一維合併變二維，一維變二維就是列的增加，舊的版本就是 y 軸的合併，表示增加 list 元素，可以用 stack 就是疊起來來記，就像往 y 軸疊東西 )

    # 通常 stack() 會比較常用來合併，因為是 append() 的作用，基本上在資料都是一維時很常會用，把所有資料都合併變成二維的 list of list

    # 例如這邊兩個 1 * 5 的 array，用列增加，所以是兩個單列五行的資料往列並排，往列增加，變成 2 * 5， 列變成 2 列

array_11 = numpy.stack((array,array_7))

print(array_11)

    # axis = 1 ( 往 x 方向增加，行的方向 )

    # 這招很常用，基本上就是把原本一維陣列反轉，再往行方向增加，比較符合一般 dataframe 資料往列方向排序，欄位往行排序的排列方式，同樣會增加維度

    # 例如這邊兩個 1 * 5 的 array，先做反轉變成 5 * 1 後，再將兩個五列一行的資料往行並排，變成 5 * 2， 行變成 2 行

array_11_2 = numpy.stack((array,array_7),axis=1)

print(array_11_2)

    # 二維 : ( 較少用 )
    
    # 合併就會變成三維，用一個更大的 list 來包住原本的兩個二維 array，所以變三維

    # axis = 0 ( 往 z 方向增加，新的方向，其實之前一維也可以這樣理解，一維原本只有 x 軸，stack 完往新的 y 軸增加 )

    # 就是兩個 2 * 3 的陣列往新的軸堆疊，新的軸就是新的 list，而原本的陣列就變成兩個元素放在裡面

array_12 = numpy.stack((array_2,array_9))

print(array_12)

    # axis = 1 ( 反轉 )

    # 就是前面 axis = 0 兩個 2 * 3 陣列合併後的反轉

array_12_1 = numpy.stack((array_2,array_9),axis=1)

print(array_12_1)

# c-3. hstack() 及 vstack()

# hstack 就是水平的疊加，是唯一 stack 裡面不會增加維度的用法，等同 concatenate 一維和二維的 axis = 1

# vstack 是把陣列先轉換成垂直方向，再往航的方向疊加，等同於 stack 一維的 axis = 1



# 3. numpy 常用的資料篩選方法

# 和 pandas dataframe 一樣，numpy array 也有自己的資料篩選方法，也是有布林陣列的方法


# a. 直接用 where() 函數

# 一維 : 

array_13 = numpy.array([0,10,20,30,40])

array_14 = numpy.where(array_13>25)

print(array_14)

# 會回傳一個 tuple 包著含有索引的 array，不會直接傳值回來，但可以用 numpy array 的進階索引來找符合的值

array_15 = array_13[array_14]

print(array_15)

# 二維 : 

array_16 = numpy.array([[0,10,20,30,40],[5,15,25,35,45]])

array_17 = numpy.where(array_16>33)

# 二維會回傳一個 tuple 包著兩個分別是 row 和 column 索引的 array，一定是兩個或多個長度一樣的 array，這樣才能有對應維度的座標

print(array_17)

# 放到 array 的進階索引就會自動把 row 和 column 兩個 indices array 對應成 (a,b) , (c,d) , (e,f) ... 的矩陣位置來找值

array_18 = array_16[array_17]

print(array_18)


# b. 用布林陣列來篩選

# 一維 : 

# 先產生一個布林陣列

# ( array 是 array > ... 陣列配合條件產生布林陣列，跟 dataframe 很像，dataframe 也是 dataframe[" "] > ... 欄位配合條件來產生布林陣列 )

array_19 = numpy.array(array_13>25)

print(array_19)

# 再套用在要篩選的陣列，就能篩選出符合條件的元素 

# ( array 是把條件放在 [ ] 裡面，就像 dataframe 的 [ ] 裡面放布林陣列來挑選資料 )

array_20 = array_13[array_19]

print(array_20)

# 二維 : 

# 就是布林陣列變成比較陣列的一樣維度而已

array_21 = numpy.array(array_2>1)

print(array_21)

# 回傳變成一個符合條件值的一維陣列

array_22 = array_2[array_21]

print(array_22)



1
2
2
[1 3 5]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 3]
 [4 6]]
[1 6]
[1 2 3]
[2 4 6]
[[1 2]
 [4 5]]
[0 1 2 3 4]
[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]]
[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]
(array([3, 4]),)
[30 40]
(array([0, 1, 1]), array([4, 3, 4]))
[40 35 45]
[False False False  True  True]
[30 40]
[[False  True  True]
 [ True  True  True]]
[2 3 4 5 6]


In [ ]:
# numpy 的其他技巧

import numpy



# 1. numpy 的一維單元素陣列可以直接當值來操作，不用做 int()

array = numpy.array([1])

a = array + 2 

print(a)



# 2. frompyfunc() 和 map() 的陣列轉換函數

# 一般的函數不支援陣列的引數和輸出，因此要用一些函數來幫助轉換成支援陣列，就像 numpy 的函數，例如 sum、log 等等，變成可以元素對元素計算

# frompyfunc 和 map 都可以做，兩者都是一個元素一個元素丟給原來函數再將獲得結果做成陣列

# frompyfunc 是支援輸出多個陣列輸入及輸出，map 只支援最多兩個輸入及一個輸出

# frompyfunc 是最後轉換完再用轉換完的函數來輸入引數，map 是直接把在轉換函數內輸入原來函數和引數


# a. frompyfunc

# 自己定義要用的函數

def sigmoid(u) :  
    
    value = 1 / (1 + numpy.exp(-u))

    return value

def add(a,b) :  

    return a + b

# 再用 frompyfun 來轉換函數成支援陣列，第二個和第三個引數分別是輸入的陣列數和輸出的陣列數

array_sigmoid = numpy.frompyfunc(sigmoid,1,1)

array_add = numpy.frompyfunc(add,2,1)

# 最後輸出就可以用轉換完的函數直接代入引數，就會自動呼叫裡面的函數來產生陣列結果

linear_y = [1,2,3]

y_prediction = array_sigmoid(linear_y)

pyfunc_add = array_add(linear_y,linear_y)

print(y_prediction)

print(pyfunc_add)


# b. map

#  一樣自己定義函數

def sigmoid(u) :  
    
    value = 1 / (1 + numpy.exp(-u))

    return value

def add(a,b) :  

    return a + b

# 用 map 來轉換成支援陣列輸入及輸出，直接輸入函數和引數

# 注意 map 輸出需要用 list 轉換才看得到

map_sigmoid = map(sigmoid,linear_y)

print(list(map_sigmoid))

map_add = map(add,linear_y,linear_y)

print(list(map_add))


# c. list 的 comprehension list 就是 frompyfunc 和 map 的一個輸入和一個輸出的用法

comprehension_list = [sigmoid(item) for item in linear_y]

print(comprehension_list)



[3]
[np.float64(0.7310585786300049) np.float64(0.8807970779778823)
 np.float64(0.9525741268224334)]
[2 4 6]
[np.float64(0.7310585786300049), np.float64(0.8807970779778823), np.float64(0.9525741268224334)]
[2, 4, 6]
[np.float64(0.7310585786300049), np.float64(0.8807970779778823), np.float64(0.9525741268224334)]


In [ ]:
# numpy 常用的基本屬性 , 方法和數學函數



import numpy 



# 1. shape() , size 

array = numpy.array([[1,2,3],[4,5,6]])

# shape 會回傳欄和列的 tuple 

print(numpy.shape(array))

# 可以再用索引取得欄和列的數量

total = numpy.shape(array)

print(total[0])

print(total[1])

# 用 size 就不用 row * column 來得到元素的總數

print(array.size)



# 2. copy() , zeros() , zeros_like()

# copy 是可以直接複製另一個陣列，zero 則是產生元素為 0 的陣列，而 zeros_like 就是兩者的結合，複製另一個陣列並把全部元素改為 0 

array_2 = numpy.copy(array)

print(array_2)

# zeros 可以指定陣列的欄和列，只要用 tuple 在引數輸入即可

array_3 = numpy.zeros(5)

array_4 = numpy.zeros((2,3))

print(array_3)

print(array_4)

# zeros_like 就是產生一個指定參考陣列的一樣大小的 0 陣列

array_5 = numpy.zeros_like(array)

print(array_5)



from numpy.random import random , rand , uniform , normal



# 3. linspace() , random() , rand() , uniform() , normal()

# 後面四個 : 

# 都是 numpy random 的隨機函數，可以用 seed() 來控制隨機種子來產生一樣的結果

# 都支援產生陣列，size 引數可以給陣列的 tuple

# 基本上後面四個隨機函數不給引數就是產生一個數字，如果有其他引數就是預設第一個引數為 0 , 第二個為 1

# 例如 uniform 就是上下界為 0 , 1 , 而 random 則是 loc = 0 , scale = 1


# a. linspace()

# linespace 是均分一個區間並產生數字

# linespace 可以指定區間，例如下面隨機產生 0 到 10 中間 20 個點

x_1 = numpy.linspace(0,10,5)

print(x_1)


# b. random() 和 rand()

# random 和 rand 都是均勻分配，隨機在 0 ~ 1 之間產生數字的隨機函數

# 差別是 random 的引數是用 tuple 來描述陣列， rand 則是 n 個引數來描述陣列

# random() 和 numpy.random 底下的 random_sample() , ranf() , sample() 都一樣

# 可以自己乘上或加上數字來調整數字區間，調整方式是 min + ( max - min ) * random，像下面就變成 0 到 2

x_2 = 2*random()

print(x_2)

# rand() 也是隨機在 0 ~ 1 之間產生數字的產生器，但是是用 n 個引數來表達陣列

x_3 = 2*rand()

print(x_3)


# c. uniform() 和 normal()

# uniform 和 normal 有一定的分配，且可以自己設定區間或平均數和標準差，比較方便控制區間

# uniform 第一個參數 low 是下界，第二個 high 是上界，最後一個 size 是產生數量

a = uniform(low=-1,high=1,size=10)

print(a)

# normal 第一個參數 loc 是平均值，第二個 scale 是標準差，最後一個 size 是產生數量

b = normal(loc=5,scale=1,size=10)

print(b)



(2, 3)
2
3
6
[[1 2 3]
 [4 5 6]]
[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]]
[[0 0 0]
 [0 0 0]]
[ 0.   2.5  5.   7.5 10. ]
1.5211663562401798
[ 0.22144747 -0.09540139 -0.52757565  0.51114629 -0.82595167  0.84017366
  0.83770613 -0.29746691 -0.33393879 -0.3695579 ]
[4.61701896 3.50162079 5.16406571 6.11615016 4.21536973 4.6418353
 4.70395519 7.10278689 5.84463677 4.5759755 ]
0.4555570715373636
0.5788897433754048


In [74]:
# numpy 資料整理的相關函數


# a. numpy 的統計描述函數


import numpy 


# 1. mean , var , std , sum , max , min

# 就是計算一群數字的統計量的函數，或者說聚合函數

array = numpy.array([1,2,3,4,5])

# sum 和 count ( 只有 count_nonzero , 元素總數是 size ) 是基本資訊

numpy_sum = numpy.sum(array)

numpy_count = array.size

print(numpy_sum)

print(numpy_count)

# mean , median 是集中量數 

numpy_mean = numpy.mean(array)

numpy_median = numpy.median(array)

print(numpy_mean)

print(numpy_median)

# var , std , max , min 是離散量數 ( 這邊的 var 是樣本的 var，是除 N - 1 )

numpy_var = numpy.var(array)

numpy_std = numpy.std(array)

numpy_min = numpy.min(array)

numpy_max = numpy.max(array)

print(numpy_var)

print(numpy_std)

print(numpy_min)

print(numpy_max)

# 2. 相關性 corvariance 和 correlation 的計算

# cov 和 corrcoef 都是產生矩陣

# 可以發現這邊 cov 的對角線是自己對自己數列的變異數 ( 這邊是除 N )，因此很接近上面 var 計算結果

array_2 = numpy.array([1,2,2,3,3])

numpy_cov = numpy.cov(array,array_2)

numpy_correlate = numpy.corrcoef(array,array_2)

print(numpy_cov)

print(numpy_correlate)


# 3. 其他統計量的計算可以用 statistics 或 scipy.stats 的統計模組


# b. 遺漏值 或 NAN 的篩選和移除




15
5
3.0
3.0
2.0
1.4142135623730951
1
5
[[2.5  1.25]
 [1.25 0.7 ]]
[[1.         0.94491118]
 [0.94491118 1.        ]]
