In [ ]:
# numpy 模組練習

    # 基本概念：numpy array 就是介於 list 和 dataframe 之間的資料結構，具有 list 的元素直接呼叫提取功能，也作為 dataframe 的基礎，可以具有欄和列

# 和 list 不同的地方 : 

    # a. array 可以是二維陣列直接提取，像是 array(0,1)

    # b. list 需要一個 list 裡面再增加 list 來增加維度，並用多層提取，像是 list[0][1]

# 和 dataframe 不同的地方 : 

    # a. array 則是基本上是 array 陣列，主要是以一維作為基礎

    # b. dataframe 一定有欄和列，是加上 row 和 column 的 index label ( 可以印 dataframe 和 array 就看得出差異，dataframe 列和欄有額外所以和標籤，array 沒有 )，
    
    # 並有 group by , merge , join 等資料庫有欄位資料的類似處理方法 

    # ex. numpy array = array( [1,2,3] , [4,5,6] )，numpy array 不需要 column

    # ex. pandas dataframe = dataframe( { a: [1,2,3] , b: [4,5,6] } )，pandas dataframe 需要 column


import numpy



# 1. numpy 基本使用方法 ( 和 list 一模一樣 , 通常是以 list 作為基礎產生 array , 只是增加可操作維度，從 [a] 變成 [a,b] )


# a. 呼叫元素

# 一維 array

array = numpy.array( [1,2,3,4,5] )

print(array[0])

# 二維 array ( 可以發現就是 list 的二維型態作為輸入來源，所以和 list 很像 )

# 每一個元素是行，每一個 list 是列，所以 array[ a,b ] 是第 a 列 , 第 b 行

# [ [a,b,c] , [d,e,f] ] 等同於 matrix 的 [ a,b,c ] 這樣擺放

#                                        [ d,e,f ]

array_2 = numpy.array( [ [1,2,3] , [4,5,6] ] )

print(array_2[0,1])

# 如果要用 list 多層呼叫方式也是可以，基本上也是先列再行的矩陣搜尋方式

print(array_2[0][1])


# b. 切片

# 一維 array 

# 和 list 一模一樣 , 就是 " 開始元素 : 結束元素 ( 不含該元素 ) : 跳幾個 "

print(array[0:5:2])

# 二維 array

# 和 dataframe 的 loc 使用類似，只是 array 可以直接操作，不用函數，就是 [ a:b , c:d ]，a:b 是列，c:d 是欄位

print(array_2[0:2,0:3])

print(array_2[:,0:3])

print(array_2[0:2,:])

# 切片也可以用 list 來選擇需要的行列 

# ( 和 dataframe 的 loc [ : , [ ... , ... ] ] 用欄位的 list 來挑選很像，

# 只是 array 是用位置索引，dataframe 是用列和欄位標籤索引 )

print(array_2[0:2,[0,2]])

# 下面和上面看起來一樣，可是只要出現兩邊相同長度的陣列，就會被自動視為進階索引的使用，而不是切片，

# 但只要兩邊不同就是切片

print(array_2[[0,1],[0,2]])


# c. 進階索引

# 可以用索引陣列 ( 或 索引 list ) 來對應相對應維度的陣列來呼叫元素，會回傳符合條件的值的一維陣列

# 這個方法比較常被 numpy 的 where() 函數使用，因為會回傳索引陣列，需要用它來找元素

# 一維 : 

# 一個 array 即可，因為是一維

print( array[ numpy.array([0,1,2]) ] )

# 二維 : 

# 兩個 array 來代表 row 和 column 的索引，因為是二維，多維就要多個 indices array

# 然後 array 長度要一樣，因為這樣所有索引才能產生相對應維度座標

print( array_2[ [0,1,1] , [1,0,2] ] )

# 二維以上可以用切片的冒號來代表一個維度，表示那一個維度的所有元素，直接讓另一個維度來對應，是不同長度的，會產生 i * j 結果

# 基本上就是降維，只剩另一個維度來挑選哪些行或哪些列

print( array_2[ : , numpy.array([0,1]) ] )


# d. 賦值

# numpy array 和 list 一樣，只要能用前面 a , b , c 方法篩選到，基本上都可以直接賦值

# ex. array[0] = 1 , array[0:1] = 2 , array[[True,True,False]] = 2 , array[numpy.array([0,1])] = 2



# 2. numpy 的常用函數


# a. arange( i,j )

# 自動產生一個 i 個元素的陣列，從 0 開始起算，j 是停止的地方，就是 range 的 array 版本，所以叫 arange

array_3 = numpy.arange(0,5)

print(array_3)


# b. rehsape( i,j )

# 把原本 array 的維度改成 i * j 的維度，例如這邊原本 2 * 3 的維度，改成 3 * 2

array_4 = array_2.reshape(3,2)

print(array_4)

# 有時候 numpy array 做為資料來源輸入某些方法時，需要是多維矩陣 array，此時可以用 reshape 把一維 array 轉成二維，多 column 標籤 ( 本質還是一維 )

# 這邊的 -1 表示指定另一個維度後自動計算 -1 的維度有幾個， (-1,1) 結果會是把原本一維的 array 內的 n 個元素拆開各自獨立的 list，因為指定 1 個 column，所以 -1 就是分到 n 個 row

array_5 = array_2.reshape(-1,2)

# 結果和 array_4 一樣，不用指定第一個參數，另一個是 2，所以 6 個元素去分一定是 3 * 2

print(array_5)

# 例如原本是 [ a,b,c ] 的陣列，是 3 個元素單維度的 array 而已，因為只有一個 list，沒有 [[]] 這樣表示，[[a,b,c]] 才是 1 * 3 維度

# 變成 [[a],[b],[c]] 就是二維裡面有 3 個 list，所以就是 3 * 1 的維度 ( 因為一個 list 就是一個 row )

array_6 = array.reshape(-1,1)

print(array_6)


# c. concatenate() 和 stack()

# 基本上就是合併， concatenate 是同一維度的合併， stack 是增加維度的合併 ( 疊更高 )

# ( concatenate 常用在陣列是一列一筆資料的陣列，然後要合併在一起，資料列變多 )

# ( stack 常用在陣列是一欄位對應的一個序列資料的陣列，然後要反轉後合併，讓原本一欄一為一列的資料變成一欄多列的資料，符合一般 dataframe 等資料常見格式 )

# c-1. concatentate() 等同 

    # 一維 :

    # list 的 extend ( 一維合併，同一維度的擴展，所以在一維就是行的增加，舊的版本就是 x 軸方向的合併，記得第一個參數要用 tuple 包起來要合併的陣列 ) 

    # axis 可以設定為 0 或 -1，但一維的結果都一樣，都是往 x 軸方向合併

array_7 = numpy.array([6,7,8,9,10])

array_8 = numpy.concatenate((array,array_7))

print(array_8)

    # 二維 : 

    # axis = 0 ( 往 y 方向，列的方向 )

    # dataframe 的 concatenate ( 二維合併，也是在二維擴展，所以在二維就是表示 list 增加，或者說 dataframe 的增加列，
    
    # 可以參考 dataframe [ [...] , [...] ] 不同日期合併的那個例子，dataframe 的 concatenate 也是同一維度合併，所以不同日期的二維 dataframe 合併後還是同樣二維的 dataframe )

    # 例如這邊兩個 2 * 3 的 array，用列增加，所以是兩個兩列單行資料往列並排，所以是往列增加，變成 4 * 3 ，列變成 4 列 

array_9 = numpy.array([[7,8,9],[10,11,12]])

array_10 = numpy.concatenate((array_2,array_9))

print(array_10)

    # axis = 1 ( 往 x 方向，行的方向 )

    # 往 x 軸方向就是把原本二維陣列用成列，再加上另一個二維陣列用成列，變成兩行，所以是行的增加，維度一樣不變

    # 例如這邊兩個 2 * 3 的 array，用行增加，所以是兩個兩列三行資料往行並排，所以是往行增加，變成 2 * 6 ，行變成 6 行

array_10_2 = numpy.concatenate((array_2,array_9),axis=1)

print(array_10_2)

# c-2. stack() 等同

    # 一維 :

    # axis = 0 ( 往 y 方向增加，列的方向 )

    # list 的 append ( 一維合併變二維，一維變二維就是列的增加，舊的版本就是 y 軸的合併，表示增加 list 元素，可以用 stack 就是疊起來來記，就像往 y 軸疊東西 )

    # 通常 stack() 會比較常用來合併，因為是 append() 的作用，基本上在資料都是一維時很常會用，把所有資料都合併變成二維的 list of list

    # 例如這邊兩個 1 * 5 的 array，用列增加，所以是兩個單列五行的資料往列並排，往列增加，變成 2 * 5， 列變成 2 列

array_11 = numpy.stack((array,array_7))

print(array_11)

    # axis = 1 ( 往 x 方向增加，行的方向 )

    # 這招很常用，基本上就是把原本一維陣列反轉，再往行方向增加，比較符合一般 dataframe 資料往列方向排序，欄位往行排序的排列方式，同樣會增加維度

    # 例如這邊兩個 1 * 5 的 array，先做反轉變成 5 * 1 後，再將兩個五列一行的資料往行並排，變成 5 * 2， 行變成 2 行

array_11_2 = numpy.stack((array,array_7),axis=1)

print(array_11_2)

    # 二維 : ( 較少用 )
    
    # 合併就會變成三維，用一個更大的 list 來包住原本的兩個二維 array，所以變三維

    # axis = 0 ( 往 z 方向增加，新的方向，其實之前一維也可以這樣理解，一維原本只有 x 軸，stack 完往新的 y 軸增加 )

    # 就是兩個 2 * 3 的陣列往新的軸堆疊，新的軸就是新的 list，而原本的陣列就變成兩個元素放在裡面

array_12 = numpy.stack((array_2,array_9))

print(array_12)

    # axis = 1 ( 反轉 )

    # 就是前面 axis = 0 兩個 2 * 3 陣列合併後的反轉

array_12_1 = numpy.stack((array_2,array_9),axis=1)

print(array_12_1)



# 3. numpy 常用的資料篩選方法

# 和 pandas dataframe 一樣，numpy array 也有自己的資料篩選方法，也是有布林陣列的方法


# a. 直接用 where() 函數

# 一維 : 

array_13 = numpy.array([0,10,20,30,40])

array_14 = numpy.where(array_13>25)

print(array_14)

# 會回傳一個 tuple 包著含有索引的 array，不會直接傳值回來，但可以用 numpy array 的進階索引來找符合的值

array_15 = array_13[array_14]

print(array_15)

# 二維 : 

array_16 = numpy.array([[0,10,20,30,40],[5,15,25,35,45]])

array_17 = numpy.where(array_16>33)

# 二維會回傳一個 tuple 包著兩個分別是 row 和 column 索引的 array，一定是兩個或多個長度一樣的 array，這樣才能有對應維度的座標

print(array_17)

# 放到 array 的進階索引就會自動把 row 和 column 兩個 indices array 對應成 (a,b) , (c,d) , (e,f) ... 的矩陣位置來找值

array_18 = array_16[array_17]

print(array_18)


# b. 用布林陣列來篩選

# 一維 : 

# 先產生一個布林陣列

# ( array 是 array > ... 陣列配合條件產生布林陣列，跟 dataframe 很像，dataframe 也是 dataframe[" "] > ... 欄位配合條件來產生布林陣列 )

array_19 = numpy.array(array_13>25)

print(array_19)

# 再套用在要篩選的陣列，就能篩選出符合條件的元素 

# ( array 是把條件放在 [ ] 裡面，就像 dataframe 的 [ ] 裡面放布林陣列來挑選資料 )

array_20 = array_13[array_19]

print(array_20)

# 二維 : 

# 就是布林陣列變成比較陣列的一樣維度而已

array_21 = numpy.array(array_2>1)

print(array_21)

# 回傳變成一個符合條件值的一維陣列

array_22 = array_2[array_21]

print(array_22)



1
2
2
[1 3 5]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]
[[1 3]
 [4 6]]
[1 6]
[1 2 3]
[2 4 6]
[[1 2]
 [4 5]]
[0 1 2 3 4]
[[1 2]
 [3 4]
 [5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[1]
 [2]
 [3]
 [4]
 [5]]
[ 1  2  3  4  5  6  7  8  9 10]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
[[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]
(array([3, 4]),)
[30 40]
(array([0, 1, 1]), array([4, 3, 4]))
[40 35 45]
[False False False  True  True]
[30 40]
[[False  True  True]
 [ True  True  True]]
[2 3 4 5 6]
